CREATE TABLE staging_flight_details (
    flight_date DATE,
    flight_status VARCHAR(50),
    aircraft VARCHAR(50),
    live VARCHAR(50),
    departure_airport VARCHAR(255),
    departure_timezone VARCHAR(255),
    departure_iata VARCHAR(10),
    departure_icao VARCHAR(10),
    departure_terminal VARCHAR(50),
    departure_gate VARCHAR(50),
    departure_delay VARCHAR(50),
    departure_scheduled TIMESTAMP,
    departure_estimated TIMESTAMP,
    departure_actual TIMESTAMP,
    departure_estimated_runway TIMESTAMP,
    departure_actual_runway TIMESTAMP,
    arrival_airport VARCHAR(255),
    arrival_timezone VARCHAR(255),
    arrival_iata VARCHAR(10),
    arrival_icao VARCHAR(10),
    arrival_terminal VARCHAR(50),
    arrival_gate VARCHAR(50),
    arrival_baggage VARCHAR(50),
    arrival_delay VARCHAR(50),
    arrival_scheduled TIMESTAMP,
    arrival_estimated TIMESTAMP,
    arrival_actual TIMESTAMP,
    arrival_estimated_runway TIMESTAMP,
    arrival_actual_runway TIMESTAMP,
    airline_name VARCHAR(255),
    airline_iata VARCHAR(10),
    airline_icao VARCHAR(10),
    flight_number VARCHAR(50),
    flight_iata VARCHAR(10),
    flight_icao VARCHAR(10),
    flight_codeshared VARCHAR(50),
    aircraft_registration VARCHAR(50),
    aircraft_iata VARCHAR(10),
    aircraft_icao VARCHAR(10),
    aircraft_icao24 VARCHAR(50),
    live_updated VARCHAR(50),
    live_latitude VARCHAR(50),
    live_longitude VARCHAR(50),
    live_altitude VARCHAR(50),
    live_direction VARCHAR(50),
    live_speed_horizontal VARCHAR(50),
    live_speed_vertical VARCHAR(50),
    live_is_ground VARCHAR(50),
    flight_codeshared_airline_name VARCHAR(255),
    flight_codeshared_airline_iata VARCHAR(10),
    flight_codeshared_airline_icao VARCHAR(10),
    flight_codeshared_flight_number VARCHAR(50),
    flight_codeshared_flight_iata VARCHAR(50),
    flight_codeshared_flight_icao VARCHAR(50)
);


COPY staging_flight_details FROM '/tmp/florida_flights.csv'
DELIMITER ','
CSV HEADER;

Select * from staging_flight_details